### Library Installation
pip install numpy

In [1]:
import numpy as np

### 1. Array Creation (Manual)

In [5]:
#1. Create a 1D Array (Manual)
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

1D Array: [1 2 3]


In [7]:
#2. Create a 2D Array (Manual using nested lists)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [15]:
#3.Create a 3D Array
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D Array:\n",arr3)
  [7 8]]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


### 2. Array Creation (Built-in Methods)

In [72]:
#1. np.zeros(shape)
#Creates an array filled with 0s.
zeros_array = np.zeros((2,3))
print("Zeros:\n", zeros_array)
print(zeros_array.ndim)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
2


In [74]:
zeros_array = np.zeros((2,3,1))
print("Zeros:\n", zeros_array)
print(zeros_array.ndim)

Zeros:
 [[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
3


In [76]:
zeros_array = np.zeros((3,3,1))
print("Zeros:\n", zeros_array)
print(zeros_array.ndim)

Zeros:
 [[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
3


In [66]:
#2. np.ones(shape)
#Creates an array filled with 1s.
ones_array = np.ones((2,3))
print("Ones:\n", ones_array)
print(ones_array.ndim)

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
2


In [68]:
ones_array = np.ones((2,3,2))
print("Ones:\n", ones_array)
print(ones_array.ndim)

Ones:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
3


In [78]:
#3. np.arange(start, stop, step)
#Creates an array with a sequence of numbers.
range_array = np.arange(1, 10, 2)
print("Arange:\n", range_array)

Arange:
 [1 3 5 7 9]


In [82]:
#np.arange(start, stop, step)
range_array = np.arange(9,50,3)
print("Arange:\n", range_array)

Arange:
 [ 9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [84]:
#np.linspace(start, stop, num)
#Returns num evenly spaced values between start and stop.
lin_array = np.linspace(0, 1, 5)
print("Linspace:\n", lin_array)

Linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [86]:
lin_array = np.linspace(3,4,3)
print("Linspace:\n", lin_array)

Linspace:
 [3.  3.5 4. ]


In [88]:
#5. np.eye(n)
#Creates an identity matrix of size n x n.
eye_matrix = np.eye(3)
print("Identity Matrix:\n", eye_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [94]:
eye_matrix = np.eye(4)
print("Identity Matrix:\n", eye_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [102]:
# 6.np.random.rand(shape)
# Generates an array of random values between 0 and 1
random_array=np.random.rand(3,5)
print("Random values:\n",random_array)

Random values:
 [[0.87720752 0.74297621 0.29170622 0.6728982  0.67494836]
 [0.43294179 0.50926809 0.51185963 0.41297792 0.02083415]
 [0.34911656 0.95092485 0.58170524 0.038967   0.77636378]]


### 3. Array Operations & Functions

In [113]:
#Arithmetic: +, -, *, / (element-wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)       
print("Subtraction:", a - b)    
print("Multiplication:", a * b) 
print("Division:", b / a)       

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


In [115]:
#Aggregates: sum(), mean(), max(), min()
arr = np.array([1, 2, 3, 4])
print("Sum:", np.sum(arr))      
print("Mean:", np.mean(arr))     
print("Max:", np.max(arr))      
print("Min:", np.min(arr))    

Sum: 10
Mean: 2.5
Max: 4
Min: 1


In [123]:
arr = np.array([[1, 2, 3],[3,4,5]])
print("Sum:", np.sum(arr))      
print("Mean:", np.mean(arr))     
print("Max:", np.max(arr))      
print("Min:", np.min(arr)) 

Sum: 18
Mean: 3.0
Max: 5
Min: 1


In [117]:
#Mathematical: np.sqrt(), np.exp(), np.log()
arr = np.array([1, 4, 9])
print("Square root:", np.sqrt(arr)) 
print("Exponent:", np.exp(arr))      
print("Logarithm:", np.log(arr))     

Square root: [1. 2. 3.]
Exponent: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
Logarithm: [0.         1.38629436 2.19722458]


In [127]:
arr = np.array([[1, 4, 9],[25,49,81]])
print("Square root:", np.sqrt(arr)) 
print("Exponent:", np.exp(arr))      
print("Logarithm:", np.log(arr))

Square root: [[1. 2. 3.]
 [5. 7. 9.]]
Exponent: [[2.71828183e+00 5.45981500e+01 8.10308393e+03]
 [7.20048993e+10 1.90734657e+21 1.50609731e+35]]
Logarithm: [[0.         1.38629436 2.19722458]
 [3.21887582 3.8918203  4.39444915]]


In [119]:
#Reshape: reshape(), flatten(), ravel()
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print("Reshaped (2x3):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened:\n", flattened)
raveled = reshaped.ravel()
print("Raveled:\n", raveled)

Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
Flattened:
 [1 2 3 4 5 6]
Raveled:
 [1 2 3 4 5 6]


### 4. Matrix Operations

In [137]:
#1.Dot product: np.dot(a, b)
# The dot product multiplies rows of the first matrix with columns of the second.
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
dot_product=np.dot(a,b)
print("Dot product:\n",dot_product)


Dot product:
 [[19 22]
 [43 50]]


In [139]:
# 2.Transpose of a Matrix(a.T)
# Transpose flips a matrix over its diagonal (rows become columns and vice versa)
matrix=np.array([[1,2,3],[4,5,6]])
print("Original Matrix:\n",matrix)
print("Transposed Matrix:\n",matrix.T)


Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


### 5. Indexing

In [143]:
#1.Accessing Elements
#You can access elements using [row][col] or [row, col]:
a = np.array([[10, 20, 30],[40, 50, 60]])
print(a[0][1])     
print(a[0, 1])

20
20


In [145]:
# 2.Boolean Indexing
#Use conditions to filter elements:
print(a > 30)       
print(a[a > 30])    

[[False False False]
 [ True  True  True]]
[40 50 60]


In [147]:
# More indexing by own
#3. Slicing Arrays
#You can slice arrays like lists:
print(a[1, :])   
print(a[:, 1])   

[40 50 60]
[20 50]


In [149]:
#4. Fancy Indexing (Indexing with a list/array of indices)
b = np.array([100, 200, 300, 400, 500])
print(b[[0, 2, 4]]) 

[100 300 500]


In [151]:
#5. Modifying Values via Indexing
a[0, 0] = 99
print(a)

[[99 20 30]
 [40 50 60]]


### 6.Slicing

In [154]:
#1D Slicing
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])     
print(a[:3])      
print(a[::2])     
print(a[-3:])     

[20 30 40]
[10 20 30]
[10 30 50]
[30 40 50]


In [156]:
#2D Slicing – Syntax: a[row_start:row_stop, col_start:col_stop]
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(b[0:2, 1:3])  
print(b[:, 1])      
print(b[1, :])     
print(b[::2, ::2])  

[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]
[[1 3]
 [7 9]]
